controller_list:
  - name: fake_r1_controller
    joints:
      - r1_joint_s
      - r1_joint_l
      - r1_joint_u
      - r1_joint_r
      - r1_joint_b
      - r1_joint_t
  - name: fake_r2_controller
    joints:
      - r2_joint_s
      - r2_joint_l
      - r2_joint_u
      - r2_joint_r
      - r2_joint_b
      - r2_joint_t
  - name: fake_dual_mh5_controller
    joints:
      - r1_joint_s
      - r1_joint_l
      - r1_joint_u
      - r1_joint_r
      - r1_joint_b
      - r1_joint_t
      - r2_joint_s
      - r2_joint_l
      - r2_joint_u
      - r2_joint_r
      - r2_joint_b
      - r2_joint_t