motoman_mh5:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - r1_joint_s
      - r1_joint_l
      - r1_joint_u
      - r1_joint_r
      - r1_joint_b
      - r1_joint_t
      - r2_joint_s
      - r2_joint_l
      - r2_joint_u
      - r2_joint_r
      - r2_joint_b
      - r2_joint_t
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: r1
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - r1_joint_s
        - r1_joint_l
        - r1_joint_u
        - r1_joint_r
        - r1_joint_b
        - r1_joint_t
    - name: r2
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - r2_joint_s
        - r2_joint_l
        - r2_joint_u
        - r2_joint_r
        - r2_joint_b
        - r2_joint_t