topic_list:
  - name: r1
    ns: mh5
    group: 0
    joints: [r1_joint_s, r1_joint_l, r1_joint_u, r1_joint_r, r1_joint_b, r1_joint_t]
  - name: r2
    ns: mh5
    group: 1
    joints: [r2_joint_s, r2_joint_l, r2_joint_u, r2_joint_r, r2_joint_b, r2_joint_t]
